[feat] 즐겨찾기 페이지를 구현한다.
prgrms-fe-devcourse/NFE1_2_Youngstar pull request #21
Opened 2024-09-29 13:25 UTC by snsdl0905

### 👀 관련 이슈
>  해결하려는 문제가 무엇인가요 ?
 
* 즐겨찾기 페이지를 디자인대로 구현했습니다.

### ✨ 작업한 내용
> 작업한 내용을 적어주세요

* 폴더를 추가하기 위한 추가 버튼이 있습니다.
* 폴더 목록들이 보입니다.

### 🌀 PR Point
> 어떤 부분을 리뷰 받았으면 좋겠나요 ? 

* 화면 크기에 따른 폴더의 크기가 괜찮은지 확인해주세요.
* 추가 버튼과 헤더 사이의 간격이 커보이는 것 같습니다. 이대로 괜찮은지, 아니면 헤더 밑에 그림자라도 넣는게 좋을 지 의견이 있다면 말해주세요.
* 

### 🍰 참고사항
>  추가로 남길 메모가 있으신가요 ?

*

### 📷 스크린샷 또는 GIF

![image](https://github.com/user-attachments/assets/05a943e8-7779-412f-8e1c-14f6188fab38)

2024-09-29 15:36 UTC, HaJun8098 commented
ㅊㄴㄴ

2024-09-30 00:46 UTC, shwnsl approved these changes
고생하셨습니다

2024-09-30 01:15 UTC, gd06070 commented
고생하셨습니다 😆 궁금한 점이 있어 몇가지 여쭤보겠습니당!! 
1. 전체화면일 때 헤더 길이가 짧은데 임시로 구현하신건거욥!?!
2. 추가 버튼 혹시 헤더 오른쪽 부분에 위치를 하고 상하 padding 10px도 괜찮아보이는데 어떠신지 궁금합니당!

2024-09-30 01:15 UTC, gd06070 requested changes
고생하셨습니다 😆 궁금한 점이 있어 몇가지 여쭤보겠습니당!! 
1. 전체화면일 때 헤더 길이가 짧은데 임시로 구현하신건거욥!?!
2. 추가 버튼 혹시 헤더 오른쪽 부분에 위치를 하고 상하 padding 10px도 괜찮아보이는데 어떠신지 궁금합니당!

2024-09-30 04:16 UTC, snsdl0905 commented
> 고생하셨습니다 😆 궁금한 점이 있어 몇가지 여쭤보겠습니당!!
> 
> 1. 전체화면일 때 헤더 길이가 짧은데 임시로 구현하신건거욥!?!
> 2. 추가 버튼 혹시 헤더 오른쪽 부분에 위치를 하고 상하 padding 10px도 괜찮아보이는데 어떠신지 궁금합니당!

말씀해주신 것 모두 수정했습니다 !

2024-09-30 04:25 UTC, snsdl0905 reviewed
수정했습니다 !

2024-09-30 05:09 UTC, snsdl0905 reviewed
수정했습니다

2024-09-30 05:10 UTC, gd06070 approved these changes
고생하셨습니당!! ,,,, git 어지럽네요 흑흑

2024-09-30 05:10 UTC, merged